### ISSUE TITLE
Call logs

### ISSUE THREAD

**Issue by benyaminmk** [benyaminmk/DefundNPD#2]
# Analysis of Newton dispatch call logs in order to assess response to low priority calls
## National analyses
Center for American Progress (CAP) and the Law Enforcement Action Partnership (LEAP) [analysis ](https://www.americanprogress.org/issues/criminal-justice/reports/2020/10/28/492492/community-responder-model/) of calls across multiple cities found a community responder model could better address the needs of low-risk 911 calls. [Their methods are public](https://docs.google.com/spreadsheets/d/1EySSsC3dDJFetqCCwzmJkPrkF5eJbJVzL1fMoZmxA2M/edit#gid=1861466124) and can inform grouping calls into low, medium, and high risk. 

## Newton Data
Call logs are [published online ](http://www.newtonpolice.com/POLICE_LOG/YEAR%202020%20POLICE%20LOG.pdf)as pdf files. Look at both 2020 and 2019 because 2020 may be skewed by COVID. We have a record of CAD types first pushed on e2c2250e361d45384fca70d4d056e898a7e7cd88

# TODO
- [x] records request for spreadsheets of 2020 and 2019 call logs
* [available here,](https://newtonma.nextrequest.com/requests/21-33) status: pending
- [ ] get list of all calls in partial log of 2020 which is already parsed into a .csv  in `data/` as `2020_npd_calls.csv` (if its not there see commit e2c2250e361d45384fca70d4d056e898a7e7cd88)
- [ ] make a prioritization table based on LEAP and CAP analysis. 
- [ ] Adjusted to remove calls that were likely officer-initiated (e.g. directed patrol) or did not receive police response (e.g. hangup calls)
